import { writeArtifact } from './artifacts.js';

export interface SystemPromptMemory {
  id: string;
  collection: string;
  content: string;
  metadata: Record<string, any>;
}

export interface SystemPromptBuildResult {
  version: number;
  companionPath: string;
  manifestPath: string;
  memoryIds: string[];
}

/**
 * Generate the companion file from the given memories and write both the
 * .md and a .manifest.json sidecar for audit.
 */
export function writeSystemPromptCompanion(
  version: number,
  memories: SystemPromptMemory[],
  thresholds: Record<string, number>,
): SystemPromptBuildResult {
  const companion = renderCompanion(version, memories);
  const manifest = renderManifest(version, memories, thresholds);

  const companionName = `v${version}.md`;
  const manifestName = `v${version}.manifest.json`;

  const companionPath = writeArtifact('system-prompt-companion', companionName, companion);
  const manifestPath = writeArtifact('system-prompt-companion', manifestName, manifest);

  return {
    version,
    companionPath,
    manifestPath,
    memoryIds: memories.map(m => m.id),
  };
}

function renderCompanion(version: number, memories: SystemPromptMemory[]): string {
  if (memories.length === 0) {
    return `# System-prompt companion v${version}\n\n_No memories met the routing thresholds for this bucket._\n`;
  }

  // Group by collection so the companion reads coherently.
  const byCollection = new Map<string, SystemPromptMemory[]>();
  for (const m of memories) {
    const arr = byCollection.get(m.collection) ?? [];
    arr.push(m);
    byCollection.set(m.collection, arr);
  }

  const lines: string[] = [
    `# System-prompt companion v${version}`,
    '',
    '_Durable, generalizable knowledge that should be available as persistent context. Generated by YAPA bucket routing._',
    '',
  ];
  const collections = [...byCollection.keys()].sort();
  for (const coll of collections) {
    lines.push(`## ${coll}`);
    lines.push('');
    for (const m of byCollection.get(coll)!) {
      lines.push(m.content);
      lines.push('');
    }
  }
  return lines.join('\n');
}

function renderManifest(
  version: number,
  memories: SystemPromptMemory[],
  thresholds: Record<string, number>,
): string {
  const payload = {
    version,
    kind: 'system-prompt-companion',
    created_at: Math.floor(Date.now() / 1000),
    thresholds,
    memory_ids: memories.map(m => m.id),
    memories: memories.map(m => ({
      id: m.id,
      collection: m.collection,
      trainable: m.metadata.trainable,
      durability: m.metadata.durability,
      generalizability: m.metadata.generalizability,
    })),
  };
  return JSON.stringify(payload, null, 2) + '\n';
}
